// <auto-generated />
namespace TafelFlyingServices.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateLayout9 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateLayout9));
        
        string IMigrationMetadata.Id
        {
            get { return "201509161535464_updateLayout9"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
