// <auto-generated />
namespace TafelFlyingServices.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatePlaneLayout2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatePlaneLayout2));
        
        string IMigrationMetadata.Id
        {
            get { return "201509152050406_updatePlaneLayout2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
